# Generated by Django 3.2.11 on 2022-02-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='estatus',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
