# Generated by Django 3.2.11 on 2022-02-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_proveedor_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='estatus',
            new_name='activo',
        ),
    ]
