# Generated by Django 3.2.11 on 2022-02-09 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0005_articulo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_name', to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='usuario_alta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_alta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='usuario_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modifica', to=settings.AUTH_USER_MODEL),
        ),
    ]
