# Generated by Django 3.2.11 on 2022-02-11 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20220209_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_articulo', to='inventario.proveedor'),
        ),
    ]
