# Generated by Django 3.2.11 on 2022-02-11 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_articulo_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('codigo_hex', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='VariacionArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variacion_articulo', to='inventario.articulo')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variacion_color', to='inventario.color')),
            ],
        ),
    ]
