# Generated by Django 3.2.11 on 2022-02-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_color_variacionarticulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacionarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variacion_list', to='inventario.articulo'),
        ),
        migrations.AlterUniqueTogether(
            name='variacionarticulo',
            unique_together={('articulo', 'color')},
        ),
    ]
