# Generated by Django 3.2.11 on 2022-02-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20220211_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='activo',
            field=models.CharField(choices=[('S', 'S'), ('N', 'N')], default='S', max_length=1),
        ),
    ]
