# Generated by Django 3.2.11 on 2022-02-07 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('ultimo_precio_compra_sin_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('ultimo_precio_compra_con_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulo_proveedor', to='api_mpadmin.proveedor')),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulo_usuario_alta', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
