# Generated by Django 3.2.11 on 2022-02-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mpadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
